languageCode = "ja"
title = "ZABURO app"
theme = "angels-ladder"
disqusShortname = "zaburoapp"
baseurl = "https://zaburo-ch.github.io/"

[Params]
subtitle = "アプリ作ったり、なんやかんや"
github = "https://github.com/zaburo-ch"
copyright = "Written by ZABURO"